package seed

import (
	"time"

	"github.com/logitrack/core/internal/model"
	"github.com/logitrack/core/internal/repository"
)

// LoadClaims siembra reclamos de muestra en todas las sucursales activas.
// Idempotente: si ya hay algún reclamo no hace nada.
func LoadClaims(claimRepo repository.ClaimRepository) {
	existing, _ := claimRepo.ListAll()
	if len(existing) > 0 {
		return
	}

	// Fechas fijas en junio 2026, entre el 1 y el 15.
	jun := func(day, hour int) time.Time {
		return time.Date(2026, time.June, day, hour, 0, 0, 0, time.UTC)
	}

	claims := []model.Claim{
		// ── CABA (origin_branch_id = 'caba') ─────────────────────────────────
		// Usar LT-CB000*, LT-MZ000*, LT-LM00007, LT-DELIVER01, LT-MZH00001
		{
			ID:               "REC-SEED001",
			TrackingID:       "LT-CB00001",
			ClaimType:        model.ClaimTypeDamage,
			Status:           model.ClaimStatusResolvedOperativa,
			Description:      "El paquete llegó con el embalaje roto y el producto dañado.",
			CreatedBy:        "chatbot-customer:31204567",
			ClaimantDNI:      "31204567",
			AssignedCategory: model.ClaimCategoryOperaciones,
			ResolutionType:   model.ClaimResolutionOperativa,
			Priority:         model.ClaimPriorityAlta,
			CreatedAt:        jun(1, 9),
			UpdatedAt:        jun(4, 14),
		},
		{
			ID:          "REC-SEED002",
			TrackingID:  "LT-CB00002",
			ClaimType:   model.ClaimTypeDelay,
			Status:      model.ClaimStatusInReview,
			Description: "El envío lleva 5 días de retraso sin novedades.",
			CreatedBy:   "chatbot-customer:27845123",
			ClaimantDNI: "27845123",
			Priority:    model.ClaimPriorityMedia,
			CreatedAt:   jun(2, 11),
			UpdatedAt:   jun(4, 10),
		},
		{
			ID:               "REC-SEED003",
			TrackingID:       "LT-CB00003",
			ClaimType:        model.ClaimTypeMissing,
			Status:           model.ClaimStatusOpen,
			Description:      "Recibí una caja pero falta un artículo del pedido.",
			CreatedBy:        "chatbot-customer:38901234",
			ClaimantDNI:      "38901234",
			AssignedCategory: model.ClaimCategorySeguros,
			Priority:         model.ClaimPriorityUrgente,
			PriorityNote:     "Escalado automático: sin actividad por más de 3 días.",
			CreatedAt:        jun(3, 8),
			UpdatedAt:        jun(10, 9),
		},
		{
			ID:               "REC-SEED004",
			TrackingID:       "LT-CB00004",
			ClaimType:        model.ClaimTypeNotDelivered,
			Status:           model.ClaimStatusResolvedComercial,
			Description:      "El chofer marcó entregado pero nunca recibí el paquete.",
			CreatedBy:        "op_caba",
			ClaimantDNI:      "25678901",
			AssignedCategory: model.ClaimCategoryComercial,
			ResolutionType:   model.ClaimResolutionComercial,
			Priority:         model.ClaimPriorityAlta,
			CreatedAt:        jun(4, 15),
			UpdatedAt:        jun(8, 16),
		},
		{
			ID:          "REC-SEED005",
			TrackingID:  "LT-CB00005",
			ClaimType:   model.ClaimTypeBadTreatment,
			Status:      model.ClaimStatusPendingCustomer,
			Description: "El repartidor fue irrespetuoso al momento de la entrega.",
			CreatedBy:   "chatbot-customer:33456789",
			ClaimantDNI: "33456789",
			Priority:    model.ClaimPriorityBaja,
			CreatedAt:   jun(5, 10),
			UpdatedAt:   jun(6, 11),
		},
		{
			ID:               "REC-SEED006",
			TrackingID:       "LT-CB00006",
			ClaimType:        model.ClaimTypeWrongData,
			Status:           model.ClaimStatusResolvedImprocedente,
			Description:      "La dirección de entrega figura incorrecta en el sistema.",
			CreatedBy:        "chatbot-sender:27845123",
			AssignedCategory: model.ClaimCategoryAdministracion,
			ResolutionType:   model.ClaimResolutionImprocedente,
			Priority:         model.ClaimPriorityBaja,
			CreatedAt:        jun(6, 9),
			UpdatedAt:        jun(9, 14),
		},
		{
			ID:          "REC-SEED007",
			TrackingID:  "LT-CB00007",
			ClaimType:   model.ClaimTypeDamage,
			Status:      model.ClaimStatusOpen,
			Description: "Producto frágil recibido completamente roto.",
			CreatedBy:   "sup_caba",
			Priority:    model.ClaimPriorityUrgente,
			CreatedAt:   jun(7, 13),
			UpdatedAt:   jun(9, 10),
		},
		{
			ID:               "REC-SEED008",
			TrackingID:       "LT-MZ00001",
			ClaimType:        model.ClaimTypeDelay,
			Status:           model.ClaimStatusResolvedOperativa,
			Description:      "Envío a Mendoza demorado más de 10 días.",
			CreatedBy:        "chatbot-customer:29001234",
			ClaimantDNI:      "29001234",
			AssignedCategory: model.ClaimCategoryOperaciones,
			ResolutionType:   model.ClaimResolutionOperativa,
			Priority:         model.ClaimPriorityMedia,
			CreatedAt:        jun(8, 10),
			UpdatedAt:        jun(12, 15),
		},
		{
			ID:          "REC-SEED009",
			TrackingID:  "LT-MZ00002",
			ClaimType:   model.ClaimTypeOther,
			Status:      model.ClaimStatusInReview,
			Description: "No recibí el comprobante de seguimiento.",
			CreatedBy:   "chatbot-customer:36789012",
			ClaimantDNI: "36789012",
			Priority:    model.ClaimPriorityBaja,
			CreatedAt:   jun(10, 14),
			UpdatedAt:   jun(12, 11),
		},
		{
			ID:               "REC-SEED00A",
			TrackingID:       "LT-DELIVER01",
			ClaimType:        model.ClaimTypeMissing,
			Status:           model.ClaimStatusResolvedComercial,
			Description:      "Falta un ítem en el paquete entregado.",
			CreatedBy:        "op_caba",
			AssignedCategory: model.ClaimCategoryComercial,
			ResolutionType:   model.ClaimResolutionComercial,
			Priority:         model.ClaimPriorityAlta,
			CreatedAt:        jun(11, 9),
			UpdatedAt:        jun(14, 16),
		},
		{
			ID:               "REC-SEED00B",
			TrackingID:       "LT-MZH00001",
			ClaimType:        model.ClaimTypeNotDelivered,
			Status:           model.ClaimStatusOpen,
			Description:      "El envío figura como entregado pero el destinatario no lo recibió.",
			CreatedBy:        "chatbot-customer:32456789",
			ClaimantDNI:      "32456789",
			Priority:         model.ClaimPriorityAlta,
			PriorityNote:     "Escalado automático: sin actividad por más de 3 días.",
			CreatedAt:        jun(13, 8),
			UpdatedAt:        jun(15, 10),
		},

		// ── CÓRDOBA ───────────────────────────────────────────────────────────
		{
			ID:               "REC-SEED010",
			TrackingID:       "LT-CDB00001",
			ClaimType:        model.ClaimTypeDelay,
			Status:           model.ClaimStatusResolvedOperativa,
			Description:      "El paquete tardó el doble de lo estimado.",
			CreatedBy:        "chatbot-customer:29876543",
			ClaimantDNI:      "29876543",
			AssignedCategory: model.ClaimCategoryOperaciones,
			ResolutionType:   model.ClaimResolutionOperativa,
			Priority:         model.ClaimPriorityMedia,
			CreatedAt:        jun(1, 10),
			UpdatedAt:        jun(5, 15),
		},
		{
			ID:           "REC-SEED011",
			TrackingID:   "LT-CDB00010",
			ClaimType:    model.ClaimTypeMissing,
			Status:       model.ClaimStatusOpen,
			Description:  "Faltan dos unidades del pedido.",
			CreatedBy:    "chatbot-customer:34567890",
			ClaimantDNI:  "34567890",
			Priority:     model.ClaimPriorityAlta,
			PriorityNote: "Escalado automático: sin actividad por más de 5 días.",
			CreatedAt:    jun(2, 11),
			UpdatedAt:    jun(10, 9),
		},
		{
			ID:               "REC-SEED012",
			TrackingID:       "LT-CDB00011",
			ClaimType:        model.ClaimTypeDamage,
			Status:           model.ClaimStatusResolvedComercial,
			Description:      "El contenido llegó mojado por embalaje deficiente.",
			CreatedBy:        "op_cordoba",
			AssignedCategory: model.ClaimCategoryComercial,
			ResolutionType:   model.ClaimResolutionComercial,
			Priority:         model.ClaimPriorityAlta,
			CreatedAt:        jun(3, 8),
			UpdatedAt:        jun(8, 17),
		},
		{
			ID:          "REC-SEED013",
			TrackingID:  "LT-CDB00012",
			ClaimType:   model.ClaimTypeOther,
			Status:      model.ClaimStatusInReview,
			Description: "No recibí comprobante de entrega.",
			CreatedBy:   "chatbot-customer:40123456",
			ClaimantDNI: "40123456",
			Priority:    model.ClaimPriorityBaja,
			CreatedAt:   jun(5, 14),
			UpdatedAt:   jun(7, 10),
		},
		{
			ID:               "REC-SEED014",
			TrackingID:       "LT-CDB00013",
			ClaimType:        model.ClaimTypeBadTreatment,
			Status:           model.ClaimStatusResolvedImprocedente,
			Description:      "Trato descortés al momento de la entrega.",
			CreatedBy:        "chatbot-customer:26543210",
			ClaimantDNI:      "26543210",
			AssignedCategory: model.ClaimCategoryRRHH,
			ResolutionType:   model.ClaimResolutionImprocedente,
			Priority:         model.ClaimPriorityBaja,
			CreatedAt:        jun(7, 9),
			UpdatedAt:        jun(11, 14),
		},
		{
			ID:          "REC-SEED015",
			TrackingID:  "LT-CDB00001",
			ClaimType:   model.ClaimTypeWrongData,
			Status:      model.ClaimStatusPendingCustomer,
			Description: "Los datos del remitente están mal cargados en el sistema.",
			CreatedBy:   "sup_cordoba",
			Priority:    model.ClaimPriorityMedia,
			CreatedAt:   jun(9, 11),
			UpdatedAt:   jun(11, 13),
		},
		{
			ID:               "REC-SEED016",
			TrackingID:       "LT-CDB00010",
			ClaimType:        model.ClaimTypeNotDelivered,
			Status:           model.ClaimStatusOpen,
			Description:      "Segundo intento de entrega fallido sin aviso.",
			CreatedBy:        "chatbot-customer:38012345",
			ClaimantDNI:      "38012345",
			Priority:         model.ClaimPriorityAlta,
			PriorityNote:     "Escalado automático: sin actividad por más de 3 días.",
			CreatedAt:        jun(11, 8),
			UpdatedAt:        jun(14, 9),
		},
		{
			ID:               "REC-SEED017",
			TrackingID:       "LT-CDB00011",
			ClaimType:        model.ClaimTypeMissing,
			Status:           model.ClaimStatusResolvedOperativa,
			Description:      "Uno de los artículos del pedido no estaba en la caja.",
			CreatedBy:        "op_cordoba",
			AssignedCategory: model.ClaimCategoryOperaciones,
			ResolutionType:   model.ClaimResolutionOperativa,
			Priority:         model.ClaimPriorityMedia,
			CreatedAt:        jun(13, 10),
			UpdatedAt:        jun(15, 16),
		},

		// ── MENDOZA ───────────────────────────────────────────────────────────
		{
			ID:               "REC-SEED020",
			TrackingID:       "LT-MZPS0001",
			ClaimType:        model.ClaimTypeDamage,
			Status:           model.ClaimStatusResolvedOperativa,
			Description:      "Botella de aceite de oliva llegó rota, todo el paquete impregnado.",
			CreatedBy:        "chatbot-customer:26543219",
			ClaimantDNI:      "26543219",
			AssignedCategory: model.ClaimCategoryOperaciones,
			ResolutionType:   model.ClaimResolutionOperativa,
			Priority:         model.ClaimPriorityUrgente,
			CreatedAt:        jun(1, 9),
			UpdatedAt:        jun(5, 11),
		},
		{
			ID:          "REC-SEED021",
			TrackingID:  "LT-MZPS0002",
			ClaimType:   model.ClaimTypeDelay,
			Status:      model.ClaimStatusOpen,
			Description: "El vino pedido lleva dos semanas sin movimientos.",
			CreatedBy:   "chatbot-customer:35219876",
			ClaimantDNI: "35219876",
			Priority:    model.ClaimPriorityMedia,
			CreatedAt:   jun(3, 10),
			UpdatedAt:   jun(5, 9),
		},
		{
			ID:               "REC-SEED022",
			TrackingID:       "LT-MZPS0003",
			ClaimType:        model.ClaimTypeNotDelivered,
			Status:           model.ClaimStatusResolvedImprocedente,
			Description:      "Dicen que entregaron pero el portón estaba cerrado.",
			CreatedBy:        "chatbot-customer:28761234",
			ClaimantDNI:      "28761234",
			AssignedCategory: model.ClaimCategoryOperaciones,
			ResolutionType:   model.ClaimResolutionImprocedente,
			Priority:         model.ClaimPriorityBaja,
			CreatedAt:        jun(5, 14),
			UpdatedAt:        jun(9, 16),
		},
		{
			ID:          "REC-SEED023",
			TrackingID:  "LT-MZPS0004",
			ClaimType:   model.ClaimTypeMissing,
			Status:      model.ClaimStatusInReview,
			Description: "Solo llegó uno de los tres vinos del pedido.",
			CreatedBy:   "sup_mendoza",
			Priority:    model.ClaimPriorityAlta,
			CreatedAt:   jun(7, 11),
			UpdatedAt:   jun(9, 10),
		},
		{
			ID:               "REC-SEED024",
			TrackingID:       "LT-MZPS0005",
			ClaimType:        model.ClaimTypeDamage,
			Status:           model.ClaimStatusResolvedComercial,
			Description:      "Caja de vinos aplastada, producto inutilizable.",
			CreatedBy:        "chatbot-customer:30123456",
			ClaimantDNI:      "30123456",
			AssignedCategory: model.ClaimCategoryComercial,
			ResolutionType:   model.ClaimResolutionComercial,
			Priority:         model.ClaimPriorityAlta,
			CreatedAt:        jun(9, 8),
			UpdatedAt:        jun(13, 15),
		},
		{
			ID:          "REC-SEED025",
			TrackingID:  "LT-MZPS0001",
			ClaimType:   model.ClaimTypeWrongData,
			Status:      model.ClaimStatusOpen,
			Description: "El número de tracking no coincide con el producto enviado.",
			CreatedBy:   "op_mendoza",
			Priority:    model.ClaimPriorityBaja,
			CreatedAt:   jun(11, 14),
			UpdatedAt:   jun(13, 11),
		},
		{
			ID:               "REC-SEED026",
			TrackingID:       "LT-MZPS0002",
			ClaimType:        model.ClaimTypeBadTreatment,
			Status:           model.ClaimStatusPendingCustomer,
			Description:      "El repartidor dejó el paquete a metros del domicilio sin avisar.",
			CreatedBy:        "chatbot-customer:37890123",
			ClaimantDNI:      "37890123",
			AssignedCategory: model.ClaimCategoryRRHH,
			Priority:         model.ClaimPriorityMedia,
			CreatedAt:        jun(13, 9),
			UpdatedAt:        jun(15, 10),
		},

		// ── POSADAS ───────────────────────────────────────────────────────────
		{
			ID:               "REC-SEED030",
			TrackingID:       "LT-POS00001",
			ClaimType:        model.ClaimTypeDelay,
			Status:           model.ClaimStatusResolvedOperativa,
			Description:      "La yerba mate llegó dos semanas tarde.",
			CreatedBy:        "chatbot-customer:30987654",
			ClaimantDNI:      "30987654",
			AssignedCategory: model.ClaimCategoryOperaciones,
			ResolutionType:   model.ClaimResolutionOperativa,
			Priority:         model.ClaimPriorityMedia,
			CreatedAt:        jun(1, 13),
			UpdatedAt:        jun(6, 15),
		},
		{
			ID:           "REC-SEED031",
			TrackingID:   "LT-POS00002",
			ClaimType:    model.ClaimTypeDamage,
			Status:       model.ClaimStatusOpen,
			Description:  "El paquete de productos regionales llegó aplastado.",
			CreatedBy:    "chatbot-customer:37654321",
			ClaimantDNI:  "37654321",
			Priority:     model.ClaimPriorityAlta,
			PriorityNote: "Escalado automático: sin actividad por más de 3 días.",
			CreatedAt:    jun(4, 9),
			UpdatedAt:    jun(12, 8),
		},
		{
			ID:               "REC-SEED032",
			TrackingID:       "LT-PSMZ0001",
			ClaimType:        model.ClaimTypeWrongData,
			Status:           model.ClaimStatusResolvedComercial,
			Description:      "Me llegó un paquete que no pedí, dirección equivocada.",
			CreatedBy:        "op_posadas",
			AssignedCategory: model.ClaimCategoryAdministracion,
			ResolutionType:   model.ClaimResolutionComercial,
			Priority:         model.ClaimPriorityBaja,
			CreatedAt:        jun(6, 10),
			UpdatedAt:        jun(10, 14),
		},
		{
			ID:          "REC-SEED033",
			TrackingID:  "LT-POS00003",
			ClaimType:   model.ClaimTypeMissing,
			Status:      model.ClaimStatusInReview,
			Description: "Falta la mitad de los artículos del pedido.",
			CreatedBy:   "chatbot-customer:28901234",
			ClaimantDNI: "28901234",
			Priority:    model.ClaimPriorityAlta,
			CreatedAt:   jun(8, 11),
			UpdatedAt:   jun(10, 13),
		},
		{
			ID:               "REC-SEED034",
			TrackingID:       "LT-PSMZ0002",
			ClaimType:        model.ClaimTypeNotDelivered,
			Status:           model.ClaimStatusResolvedImprocedente,
			Description:      "El envío figura entregado pero el local estaba cerrado ese día.",
			CreatedBy:        "chatbot-customer:39234567",
			ClaimantDNI:      "39234567",
			AssignedCategory: model.ClaimCategoryOperaciones,
			ResolutionType:   model.ClaimResolutionImprocedente,
			Priority:         model.ClaimPriorityBaja,
			CreatedAt:        jun(10, 8),
			UpdatedAt:        jun(13, 16),
		},
		{
			ID:          "REC-SEED035",
			TrackingID:  "LT-PSMZ0003",
			ClaimType:   model.ClaimTypeBadTreatment,
			Status:      model.ClaimStatusOpen,
			Description: "Actitud hostil del personal al intentar reclamar en la sucursal.",
			CreatedBy:   "sup_posadas",
			Priority:    model.ClaimPriorityMedia,
			CreatedAt:   jun(12, 14),
			UpdatedAt:   jun(14, 9),
		},

		// ── SANTA CRUZ ────────────────────────────────────────────────────────
		{
			ID:               "REC-SEED040",
			TrackingID:       "LT-PROJ0001",
			ClaimType:        model.ClaimTypeMissing,
			Status:           model.ClaimStatusOpen,
			Description:      "Recibí el paquete exterior pero el contenido estaba vacío.",
			CreatedBy:        "chatbot-customer:22345678",
			ClaimantDNI:      "22345678",
			AssignedCategory: model.ClaimCategorySeguros,
			Priority:         model.ClaimPriorityUrgente,
			CreatedAt:        jun(2, 8),
			UpdatedAt:        jun(7, 11),
		},
		{
			ID:          "REC-SEED041",
			TrackingID:  "LT-PROJ0002",
			ClaimType:   model.ClaimTypeDelay,
			Status:      model.ClaimStatusInReview,
			Description: "Más de 20 días sin movimiento del envío.",
			CreatedBy:   "sup_santa_cruz",
			Priority:    model.ClaimPriorityAlta,
			CreatedAt:   jun(4, 15),
			UpdatedAt:   jun(6, 13),
		},
		{
			ID:               "REC-SEED042",
			TrackingID:       "LT-PROJ0003",
			ClaimType:        model.ClaimTypeDamage,
			Status:           model.ClaimStatusResolvedOperativa,
			Description:      "Equipo electrónico llegó con golpe visible en la carcasa.",
			CreatedBy:        "chatbot-customer:39012345",
			ClaimantDNI:      "39012345",
			AssignedCategory: model.ClaimCategoryOperaciones,
			ResolutionType:   model.ClaimResolutionOperativa,
			Priority:         model.ClaimPriorityMedia,
			CreatedAt:        jun(6, 9),
			UpdatedAt:        jun(10, 16),
		},
		{
			ID:               "REC-SEED043",
			TrackingID:       "LT-PROJ0001",
			ClaimType:        model.ClaimTypeNotDelivered,
			Status:           model.ClaimStatusResolvedComercial,
			Description:      "El envío figura en el sistema como entregado pero nunca llegó.",
			CreatedBy:        "chatbot-customer:25678901",
			ClaimantDNI:      "25678901",
			AssignedCategory: model.ClaimCategoryComercial,
			ResolutionType:   model.ClaimResolutionComercial,
			Priority:         model.ClaimPriorityAlta,
			CreatedAt:        jun(8, 10),
			UpdatedAt:        jun(12, 14),
		},
		{
			ID:          "REC-SEED044",
			TrackingID:  "LT-PROJ0002",
			ClaimType:   model.ClaimTypeBadTreatment,
			Status:      model.ClaimStatusPendingCustomer,
			Description: "El operador fue grosero al informar sobre el estado del envío.",
			CreatedBy:   "chatbot-customer:31234567",
			ClaimantDNI: "31234567",
			Priority:    model.ClaimPriorityBaja,
			CreatedAt:   jun(10, 11),
			UpdatedAt:   jun(12, 10),
		},
		{
			ID:               "REC-SEED045",
			TrackingID:       "LT-PROJ0003",
			ClaimType:        model.ClaimTypeWrongData,
			Status:           model.ClaimStatusOpen,
			Description:      "La dirección de entrega registrada no corresponde al domicilio real.",
			CreatedBy:        "sup_santa_cruz",
			AssignedCategory: model.ClaimCategoryAdministracion,
			Priority:         model.ClaimPriorityMedia,
			PriorityNote:     "Escalado automático: sin actividad por más de 3 días.",
			CreatedAt:        jun(12, 8),
			UpdatedAt:        jun(15, 9),
		},
	}

	for i := range claims {
		_ = claimRepo.Create(claims[i])
	}
}
